import Head from 'next/head'
import {Button, Box,Switch} from "@chakra-ui/react"
import Layout from "../layouts"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          Hello nextjs
          <Button>test</Button>
          <Button variant="solid" bg="primary">primary</Button>
        </div>
        <div>
            <Switch size='md' />
        </div>
        <Box fontSize="lg" fontWeight="thin">
            my size is is  
        </Box>
      </main>
    </div>
  )
}
Home.getLayout = function(page) {
  return <Layout>{page}</Layout>
}
