import Head from 'next/head'
import {Button, Box,Switch} from "@chakra-ui/react"
import Layout from "../layouts/index"
import Banner from "../components/banner"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box minH="90vh">
        <Box fontSize="lg" fontWeight="thin">
            my size is is  
        </Box>
        </Box>
      </main>
    </div>
  )
}
Home.getLayout = function(page) {
  return <Layout>{page}</Layout>
}
